#!/usr/bin/env python
"""Generate strong secrets for THIS install and (with --write) put them in
backend/.env. Every client / every server must have its own.

    cd backend
    python scripts/gen_secrets.py            # just print new values
    python scripts/gen_secrets.py --write    # write backend/.env (+ backup)

What it sets: JWT_SECRET, EMBEDDING_ENCRYPTION_KEY, KIOSK_SERVICE_TOKEN
(shared legacy camera token; prefer per-camera tokens from Settings ->
Cameras and then run with --no-shared-kiosk-token), APP_ENV=production.

EMBEDDING_ENCRYPTION_KEY is the master key that protects stored face
templates. If face templates already exist, --write re-encrypts them with
the new key in the same run (envelope encryption: only the small per-record
keys are re-wrapped), so nothing has to be enrolled again. Keep a copy of
backend/.env in a safe place: without the key, stored face data can't be
read.

Afterwards: restart the backend; logged-in users must log in again; cameras
using the shared token need the new KIOSK_SERVICE_TOKEN in their .env.
"""
from __future__ import annotations

import argparse
import asyncio
import secrets
import shutil
import sys
from datetime import datetime
from pathlib import Path

from cryptography.fernet import Fernet

BACKEND = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BACKEND))
ENV_PATH = BACKEND / ".env"


def new_values(shared_kiosk: bool) -> dict[str, str]:
    return {
        "APP_ENV": "production",
        "JWT_SECRET": secrets.token_urlsafe(48),
        "EMBEDDING_ENCRYPTION_KEY": Fernet.generate_key().decode(),
        "KIOSK_SERVICE_TOKEN": secrets.token_urlsafe(32) if shared_kiosk else "",
    }


def merge_env(text: str, values: dict[str, str]) -> str:
    out, seen = [], set()
    for line in text.splitlines():
        key = line.split("=", 1)[0].strip() if "=" in line and not line.lstrip().startswith("#") else None
        if key in values:
            out.append(f"{key}={values[key]}")
            seen.add(key)
        else:
            out.append(line)
    missing = [k for k in values if k not in seen]
    if missing:
        out.append("")
        out.append(f"# --- generated by scripts/gen_secrets.py on {datetime.now():%Y-%m-%d %H:%M} ---")
        out += [f"{k}={values[k]}" for k in missing]
    return "\n".join(out) + "\n"


async def rewrap_templates(old_key: str, new_key: str) -> int:
    from sqlalchemy import select

    from app.db import AsyncSessionLocal, engine
    from app.models.face_templates import FaceTemplate
    from app.security import rewrap_embedding

    n = 0
    try:
        async with AsyncSessionLocal() as db:
            for t in (await db.execute(select(FaceTemplate))).scalars().all():
                t.embedding_encrypted = rewrap_embedding(t.embedding_encrypted, old_key, new_key)
                n += 1
            await db.commit()
    finally:
        await engine.dispose()
    return n


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--write", action="store_true", help="write backend/.env (a backup is kept)")
    ap.add_argument("--no-shared-kiosk-token", action="store_true",
                    help="disable the shared camera token (every camera uses its own token)")
    ap.add_argument("--keep-kiosk-token", action="store_true", help="don't change KIOSK_SERVICE_TOKEN")
    args = ap.parse_args()

    values = new_values(shared_kiosk=not args.no_shared_kiosk_token)
    if args.keep_kiosk_token:
        values.pop("KIOSK_SERVICE_TOKEN")
    if not args.write:
        for k, v in values.items():
            print(f"{k}={v}")
        print("\n(nothing written -- run with --write to update backend/.env)")
        return

    from app.config import get_settings

    old_key = get_settings().embedding_encryption_key
    text = ENV_PATH.read_text(encoding="utf-8") if ENV_PATH.exists() else ""
    if ENV_PATH.exists():
        backup = ENV_PATH.with_name(f".env.backup-{datetime.now():%Y%m%d-%H%M%S}")
        shutil.copy2(ENV_PATH, backup)
        print(f"backup: {backup}")

    n = asyncio.run(rewrap_templates(old_key, values["EMBEDDING_ENCRYPTION_KEY"]))
    ENV_PATH.write_text(merge_env(text, values), encoding="utf-8")
    print(f"OK: wrote {ENV_PATH}")
    print(f"    re-encrypted {n} face template(s) with the new master key")
    if "KIOSK_SERVICE_TOKEN" in values:
        tok = values["KIOSK_SERVICE_TOKEN"]
        print("    cameras on the shared token: set in each camera's .env ->",
              f"KIOSK_SERVICE_TOKEN={tok}" if tok else "use per-camera tokens (Settings -> Cameras)")
    print("Restart the backend now. Everyone has to log in again.")


if __name__ == "__main__":
    main()
